"""empty message

Revision ID: 0625d55d47de
Revises: e12ea0c468b5
Create Date: 2021-03-23 11:25:02.150874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '0625d55d47de'
down_revision = 'e12ea0c468b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_comments',
    sa.Column('parent_comment_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('post_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('parent_comment_id')
    )
    op.create_table('child_comments',
    sa.Column('child_comment_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('parent_comment_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('reply_user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['parent_comments.parent_comment_id'], ),
    sa.ForeignKeyConstraint(['reply_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('child_comment_id')
    )
    op.drop_table('comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('comment_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('post_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('user_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('parent_comment_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=32), nullable=True),
    sa.Column('content', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=False),
    sa.Column('create_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.comment_id'], name='comments_ibfk_1'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], name='comments_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='comments_ibfk_3'),
    sa.PrimaryKeyConstraint('comment_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('child_comments')
    op.drop_table('parent_comments')
    # ### end Alembic commands ###
