"""empty message

Revision ID: cf831f5db5b6
Revises: 
Create Date: 2021-03-17 12:03:09.951729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf831f5db5b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('followee_counts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('follower_counts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'follower_counts')
    op.drop_column('users', 'followee_counts')
    # ### end Alembic commands ###
