"""empty message

Revision ID: e12ea0c468b5
Revises: cf831f5db5b6
Create Date: 2021-03-22 11:38:12.832937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e12ea0c468b5'
down_revision = 'cf831f5db5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('like_counts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'like_counts')
    # ### end Alembic commands ###
