"""empty message

Revision ID: fd5ccf0e8a2c
Revises: c42839c4e729
Create Date: 2021-03-23 17:55:30.948833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5ccf0e8a2c'
down_revision = 'c42839c4e729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('comment_counts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'comment_counts')
    # ### end Alembic commands ###
