version: "3"

services:
  web:
    container_name: web
    image: nginx
    depends_on:
      - app
      - maria_db
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - nginx-app-network
    restart: always
  app:
    container_name: app
    build:
      dockerfile: ./docker/app/Dockerfile
      context: ../.
    working_dir: /app
    depends_on:
      - maria_db
    volumes:
      - ../src:/app
    ports:
      - "5000:5000"
    tty: true
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: app.py
      FLASK_ENV: development
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: door_out_db
      MYSQL_USER: door_out_user
      MYSQL_PASSWORD: w6lCQ2THZVXDBMAWBc1xlpSuGEKEwzFd
      DATABASE_CONTAINER_NAME: maria_db

    command: wait-for-it.sh maria_db:3306 --timeout=30 -- python app.py
    networks:
      - app-db-network
      - nginx-app-network
    restart: always

  maria_db:
    container_name: maria_db
    build: ./maria_db/
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: door_out_db
      MYSQL_USER: door_out_user
      MYSQL_PASSWORD: w6lCQ2THZVXDBMAWBc1xlpSuGEKEwzFd
    ports:
      - "3306:3306"
    tty: true
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - app-db-network
    restart: always


networks:
  app-db-network:
    driver: bridge
  nginx-app-network:
    driver: bridge
